apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.digitalocean.com/load-balancer-name: "arkive-webapp"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "bf7fdde5-8825-45ad-bc9e-ef2e9dd76723"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
  name: arkive-webapp-service
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9080
  selector:
    app: arkive-webapp
  type: LoadBalancer
